server:
  port: 8083

spring:
  application: # Fix: Changed application name to 'account-service'
    name: account-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
