version: '3.8'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  account-service:
    build: ./account-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  transaction-service:
    build: ./transaction-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - account-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker